
name: 'Godot Engine 4.x Web Export linux'
description: 'Godot Engine 4.x Web export linux'
author: 'Simon Dalvai @dulvui with deletes by digiur'
branding:
  color: blue
  icon: upload-cloud

inputs:
  working-directory:
    description: 'The working directory'
    required: false
    default: '.'
  output-file-path:
    description: 'Path of the exported html files'
    required: false
    default: 'html5/index.html'
  create-export-preset-cfg:
    description: 'Set true if a simple export_presets.cfg should be created'
    required: false
    default: true
  godot-version:
    description: 'Godot Engine version. Supported are 4.x versions'
    required: false
    default: '4.2.2'
  os:
    description: 'The runners OS. Linux and Windows supported'
    required: false
    default: 'Linux'
  
runs:
  using: "composite"
  steps:
    # - name: Check is running on Linux
    #   if: runner.os != 'Linux'
    #   shell: bash
    #   run: exit 1

    - name: Define TEMPLATE_DIR
      shell: bash
      run: echo "TEMPLATE_DIR=~/.local/share/godot/export_templates/${{ inputs.godot-version }}.stable" >> $GITHUB_ENV

    - name: Create export paths directory structure
      shell: bash
      run: mkdir -p "$(dirname ${{ inputs.output-file-path }})"

    - name: Download Godot Engine linux server
      shell: bash
      run: |
        wget -q https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_linux.x86_64.zip

    - name: Download Godot Engine templates
      shell: bash
      run: |
        wget -q https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_export_templates.tpz

    - name: Unzip Godot Engine linux server and templates
      shell: bash
      run: |
        unzip Godot_v4.2.2-stable_linux.x86_64.zip
        unzip Godot_v4.2.2-stable_export_templates.tpz

    - name: Move Templates
      shell: bash
      run: |
        mkdir -p ${{ env.TEMPLATE_DIR }}
        mv templates/* ${{ env.TEMPLATE_DIR }}

    - name: Remove Downloads
      shell: bash
      run: |
        rm -f https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_linux.x86_64.zip https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_export_templates.tpz

    - name: Export Godot project to html
      shell: bash
      run: ./Godot_v4.2.2-stable_linux.x86_64 --headless --path ${{ inputs.working-directory }} --export-release ballistic-space-miner-html5 ${{ inputs.output-file-path }}
